Numpaar Extensions by DebugIto
==============================

This repository provides various extensions (engines and scripts) used in Numpaar_.

.. _Numpaar: https://github.com/debug-ito/numpaar

The extensions are totally for my personal use for now...


Author
------

- Toshio ITO
- debug.ito [at] gmail.com



